### ISSUE TITLE
Can't add custom repository

### ISSUE THREAD

**Issue by wffbos** [nobodyguy/ha_prusaconnect_webcam_uploader_integration#1]
Trying to add custom HACS repository on HA 2024.11.1 with HACS 2.0.1 gives me the error message:

> <Integration nobodyguy/ha_prusaconnect_webcam_uploader_integration> Repository structure for main is not compliant

**Comment by nobodyguy** [comment]
Thank you for the report. It should work now.

**Comment by wffbos** [comment]
Thanks for the quick fix! I can now add without any problems.
